language: python
python:
  - "3.6"
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: karma0
  password:
    secure: b4Itsj7CFPCDY+0n0hmUI3KImQTlQOOVrdvQ7+ytC9YsQLWEaPTNzuGp3AF57geQ9DGYLbGlNBjiN143qiawL6zwsq8sH+3I4uPvN/cBKx9OYjizAY0Q3XUx6ysKIw6gmp4ydFtMeJB0vBxdpjyeC4NrMd6kII62rTwFPq7eKAZU+noU5D3x/npJOK0jfRZ+LjACB57DSEvtrk+RMV19dkNWQ9jb92UNElohWSUYjpBjAnrmoChLgT9D1tKs+hAeDNLrnD7GD5EyZagSqIYJKRaZbmVN09CxcYv95a24mkm2KhqDg9zwyUJU4SJgBtLZxAWrXjlLXrXg10Sdx9HA7db6N7hmTFvdNjM+rUdLpGIQ87lgagMcyL52wgoc0y1zSViQn06EKaYSLP6+AOSnMesUKjTF0lPX5fUZKOg0JQ3M2dxfdBiwCPzGvLyCUX0iFf/atW/1RkeEEgw3jRHYsKc4q5+PHg4F3Zlz3kac+DE423cWk9ldEyKgB3UITS9uxSR6QI80oZT9FcIrDUDk/Mw/6imz7gi4TWQUwfVHRy9EkwTfns197bYDN84/Gca+wO5YhRNEMcIfzqTG0E0YWnDYtHhjXfGseM/+Vv3JTkE4eVpTYsWQo2GpBbHYb76fKZ5VEvYGa1isRg2loEyROY2WCG4CgHm/spHRzlNQnkg=
  on:
    tags: true
    repo: karma0/nombot
    python: 3.6
